const LOGIN_SET_API_URL = "LOGIN_SET_API_URL";
const SET_CURRENT_USERNAME = "SET_CURRENT_USERNAME";
const SET_CURRENT_USER_AUTHORITY = "SET_CURRENT_USERNAME_AUTHORITY";
const HOME_OPEN_MODULE = "HOME_OPEN_MODULE";
const HOME_CLOSE_MODULE = "HOME_CLOSE_MODULE";
const HOME_TOGGLE_CURRENT_MODULE = "HOME_TOGGLE_CURRENT_MODULE";

export {
    LOGIN_SET_API_URL,
    SET_CURRENT_USERNAME,
    SET_CURRENT_USER_AUTHORITY,
    HOME_OPEN_MODULE,
    HOME_CLOSE_MODULE,
    HOME_TOGGLE_CURRENT_MODULE
};